### ISSUE TITLE
Typo in ServiceRegisteDescriptor

### ISSUE THREAD

**Issue by jradxl** [dxp909/DependencyInjectionScan#1]
Hi,
Typo in "ServiceRegisteDescriptor" should be "ServiceRegisterDescriptor"
(Add an "r" to make the word "Register".

I'm so sorry to report something so small as a typo, but since this is your first commit it's easy to fix.

Brilliant idea. Thanks for posting

**Comment by dxp909** [comment]
thanks for your report,i have changed code.
